### ISSUE TITLE
would it be possible to gzip the files?

### ISSUE THREAD

**Issue by rich-murphey** [kilork/actix-web-static-files#4]
It could reduce executable size, if there were an option to gzip the static files, and have the service set the content type.  Just a thought.

**Comment by kilork** [comment]
Good idea, thanks, I think we can add this as a feature.

**Comment by rich-murphey** [comment]
Thanks for considering it. If there's anything I can do to help, I'd be glad to. My use case is bundling 'npm build release' results.

**Comment by IronOxidizer** [comment]
As an alternative, the user should gzip their own files which would be detected (suffix `.gz`) and embedded in the binary. `static-files` would then respond with the gzipped version if the request contained `Accept-Encoding: gzip`.

This would function very similarly to NginX `gzip_static on` (except better since no read is needed, files are already in memory) which is the ideal way to serve compressed static files.

**Comment by kilork** [comment]
I actually thought exactly about this, as preferred way to handle this.

We can at the end have 4 non exclusive options:
- resolve resource with .gz for case, when it is already prepared by user
- gzip selected resources during compile time and then basically fallback to first approach
- gzip selected resources during runtime (I see this as no-go option, because of design complications)
- ungzip resources, if we do not have original static resource (not so complicated to implement, drawback I see here is the additional runtime dependency)

In any case this option would be added with a feture flag, so only those, who really need one of the options - would get it.

I see people still using this library, so I hope to find time to develop these features at least one by one.

**Comment by IronOxidizer** [comment]
> - resolve resource with .gz for case, when it is already prepared by user

I'll see if I can try implementing this some time this week. It shouldn't be too difficult:

https://users.rust-lang.org/t/how-to-serve-a-pre-compressed-data-with-actix-web/16822

**Comment by kilork** [comment]
Just think about how to do this from api-perspective. This should not have side effects, means, if someone already had .gz it should not just start to serve them.

I think we need to have separate optional input parameter with root directory to search pairs for our original files and shortcut function, to just enable with using default directory (same as original one).

**Comment by kilork** [comment]
I plan to implement it, actually.
